import React from 'react';
import { usePlagShield } from '../../hooks/PlagShieldContext';
import { useNavigate } from 'react-router-dom';
import { Activity, LayoutGrid, Network, Users, Download, CheckCircle2, AlertTriangle, ShieldAlert, FileCode2 } from 'lucide-react';
import SimilarityHeatmap from '../../components/SimilarityHeatmap';
import GraphView from '../../components/views/GraphView';
import AnalyticsDashboard from '../../components/views/AnalyticsDashboard';

export default function ResultsPage() {
  let ctx;
  try {
    ctx = usePlagShield();
  } catch(e) {
    return (
      <div className="card p-12 text-center">
        <p className="text-[var(--text-primary)] font-bold">Context unavailable</p>
        <p className="text-sm text-[var(--text-secondary)] mt-2">{e.message}</p>
      </div>
    );
  }

  const { 
    results, 
    riskThreshold = 75, 
    suspiciousThreshold = 40, 
    handlePairSelection, 
    preferences = {},
    summaryTiles = [],
    fileStats = { total: 0, highRisk: 0, suspicious: 0, safe: 0 },
    semanticResults,
    isSemanticLoading,
    normalizedRings = [],
    getPairScore,
    activeBatch
  } = ctx;

  const navigate = useNavigate();

  if (!results) {
    return (
      <div className="card p-12 flex flex-col items-center justify-center text-center">
        <Activity size={48} className="text-[var(--text-tertiary)] mb-4" />
        <h2 className="text-xl font-bold text-[var(--text-primary)]">No Analysis Results</h2>
        <p className="text-[var(--text-secondary)] mt-2">Open an investigation from the Analysis Library to view results.</p>
      </div>
    );
  }

  const students = results?.students || [];
  const tiles = Array.isArray(summaryTiles) ? summaryTiles : [];

  return (
    <div className="space-y-8 animate-in fade-in duration-500 print:space-y-6 print:bg-white print:text-black">
      
      {/* Formal Academic Print Header (Only visible in PDF) */}
      <div className="hidden print:block border-b-4 border-gray-800 pb-6 mb-8 mt-4">
        <div className="flex justify-between items-end">
          <div>
            <h1 className="text-4xl font-serif font-bold text-gray-900 mb-2">Plagiarism Analysis Report</h1>
            <p className="text-lg text-gray-600 font-serif">Generated by PlagShield Engine v2.0</p>
          </div>
          <div className="text-right text-sm text-gray-700 font-mono">
            <p className="mb-1"><span className="font-bold">Batch ID:</span> {activeBatch || 'N/A'}</p>
            <p className="mb-1"><span className="font-bold">Date:</span> {new Date().toLocaleDateString()}</p>
            <p><span className="font-bold">Submissions:</span> {students.length}</p>
          </div>
        </div>
      </div>

      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 print:hidden">
        <div>
          <h1 className="text-2xl font-bold text-[var(--text-primary)] flex items-center gap-2">
            <Network className="text-[var(--accent)]" size={24} /> Results Summary
          </h1>
          <p className="mt-1 text-sm text-[var(--text-secondary)]">High-level insights and similarity distribution.</p>
        </div>
        <div className="flex items-center gap-3">
          <button 
            onClick={() => window.print()}
            className="btn-secondary py-2 px-4 text-sm font-medium flex items-center gap-2"
          >
            <Download size={16} />
            Export PDF
          </button>
        </div>
      </div>

      {/* Pair Summary Tiles */}
      {tiles.length > 0 && (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 print:grid-cols-4 print:gap-4 print:mb-8">
          {tiles.map((tile, idx) => (
            <div key={idx} className="card p-5 relative overflow-hidden group hover:border-[var(--accent)] transition-colors print:border-gray-300 print:shadow-none print:rounded-none">
              <div className="absolute -right-4 -top-4 opacity-5 group-hover:opacity-10 transition-opacity print:hidden">
                <Activity size={100} />
              </div>
              <p className="text-[11px] font-bold uppercase tracking-wider text-[var(--text-tertiary)] mb-2 relative z-10 print:text-gray-500">{tile.label}</p>
              <p className="text-3xl font-extrabold text-[var(--text-primary)] relative z-10 print:text-black">{tile.value}</p>
            </div>
          ))}
        </div>
      )}

      {/* Narrative Bullet Summary */}
      <div className="card p-6 bg-[var(--bg-secondary)]/50 border border-[var(--border-default)] print:bg-white print:border-gray-300">
        <h3 className="text-sm font-bold text-[var(--text-primary)] mb-4 uppercase tracking-wider print:text-gray-900">Analysis Breakdown</h3>
        <ul className="space-y-3">
          <li className="flex items-start gap-3">
            <FileCode2 className="text-[var(--text-tertiary)] shrink-0 mt-0.5" size={18} />
            <span className="text-sm text-[var(--text-secondary)]">
              <strong className="text-[var(--text-primary)]">Batch Overview:</strong> Successfully processed and fingerprinted <strong className="text-[var(--text-primary)]">{fileStats.total} total files</strong> in this submission folder.
            </span>
          </li>
          {fileStats.highRisk > 0 && (
            <li className="flex items-start gap-3">
              <ShieldAlert className="text-[var(--danger)] shrink-0 mt-0.5" size={18} />
              <span className="text-sm text-[var(--text-secondary)]">
                <strong className="text-[var(--danger)]">Plagiarism Detected:</strong> <strong className="text-[var(--text-primary)]">{fileStats.highRisk} files</strong> exhibit high-risk structural and semantic overlap exceeding the strict threshold ({riskThreshold}%). Immediate investigation recommended.
              </span>
            </li>
          )}
          {fileStats.suspicious > 0 && (
            <li className="flex items-start gap-3">
              <AlertTriangle className="text-[var(--warning)] shrink-0 mt-0.5" size={18} />
              <span className="text-sm text-[var(--text-secondary)]">
                <strong className="text-[var(--warning)]">Potential Overlap:</strong> <strong className="text-[var(--text-primary)]">{fileStats.suspicious} files</strong> show suspicious similarity patterns ({suspiciousThreshold}% - {riskThreshold}%) that may indicate shared boilerplates or unauthorized collaboration.
              </span>
            </li>
          )}
          <li className="flex items-start gap-3">
            <CheckCircle2 className="text-[var(--success)] shrink-0 mt-0.5" size={18} />
            <span className="text-sm text-[var(--text-secondary)]">
              <strong className="text-[var(--success)]">Safe Submissions:</strong> <strong className="text-[var(--text-primary)]">{fileStats.safe} files</strong> ({Math.round((fileStats.safe / (fileStats.total || 1)) * 100)}%) were found to be completely independent with no significant similarities to peers.
            </span>
          </li>
        </ul>
      </div>

      {/* File Status Summary */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4 print:grid-cols-4 print:gap-4">
        <div className="card p-5 border-l-4 border-l-gray-400">
          <p className="text-[11px] font-bold uppercase tracking-wider text-[var(--text-tertiary)] mb-1">Total Files</p>
          <p className="text-3xl font-extrabold text-[var(--text-primary)]">{fileStats.total}</p>
        </div>
        <div className="card p-5 border-l-4 border-l-[var(--success)] bg-[var(--success)]/5">
          <p className="text-[11px] font-bold uppercase tracking-wider text-[var(--success)] mb-1">Safe Files</p>
          <p className="text-3xl font-extrabold text-[var(--success)]">{fileStats.safe}</p>
        </div>
        <div className="card p-5 border-l-4 border-l-[var(--warning)] bg-[var(--warning)]/5">
          <p className="text-[11px] font-bold uppercase tracking-wider text-[var(--warning)] mb-1">Suspicious Files</p>
          <p className="text-3xl font-extrabold text-[var(--warning)]">{fileStats.suspicious}</p>
        </div>
        <div className="card p-5 border-l-4 border-l-[var(--danger)] bg-[var(--danger)]/5">
          <p className="text-[11px] font-bold uppercase tracking-wider text-[var(--danger)] mb-1">High Risk Files</p>
          <p className="text-3xl font-extrabold text-[var(--danger)]">{fileStats.highRisk}</p>
        </div>
      </div>

      {/* Visual Analytics Dashboard (Donut, Bar Charts) */}
      <AnalyticsDashboard results={results} fileStats={fileStats} />

      {/* Heatmap */}
      {students.length > 0 && (
        <section className="card p-6 print:border-none print:shadow-none print:p-0 print:mb-8">
          <div className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
            <h3 className="text-sm font-bold text-[var(--text-primary)] flex items-center gap-2 uppercase tracking-wider print:text-gray-900 print:text-lg print:border-b print:border-gray-300 print:pb-2 print:w-full">
              <LayoutGrid size={16} className="text-[var(--text-secondary)] print:hidden" /> Similarity Matrix
            </h3>
            <div className="flex items-center gap-3 print:hidden">
              <span className="badge badge-neutral bg-[var(--bg-secondary)] border-[var(--border-default)]">
                {students.length} submissions
              </span>
            </div>
          </div>
          <div className="relative border border-[var(--border-default)] rounded-xl overflow-hidden bg-[var(--bg-secondary)] p-4 print:border-gray-300 print:rounded-none print:bg-white">
            <SimilarityHeatmap
              data={results}
              thresholds={{ highRisk: riskThreshold, suspicious: suspiciousThreshold }}
              animateCells={preferences?.animateHeatmap ?? true}
              onPairSelect={(pair) => {
                if (handlePairSelection) handlePairSelection(pair);
                navigate('/analyses/latest/compare');
              }}
            />
          </div>
        </section>
      )}

      <div className="space-y-8 print:space-y-12 print:break-before-page">
        {/* Graph */}
        <section className="card p-6 print:border-none print:shadow-none print:p-0">
          <h3 className="text-sm font-bold text-[var(--text-primary)] flex items-center gap-2 uppercase tracking-wider mb-6 print:text-gray-900 print:text-lg print:border-b print:border-gray-300 print:pb-2">
            <Network size={16} className="text-[var(--text-secondary)] print:hidden" /> Semantic Graph
          </h3>
          <div className="relative -mx-6 print:mx-0">
            <GraphView semanticResults={semanticResults} isSemanticLoading={isSemanticLoading} />
          </div>
        </section>
      </div>
    </div>
  );
}
