import React from 'react';
import { usePlagShield } from '../../hooks/PlagShieldContext';
import { useNavigate } from 'react-router-dom';
import {
  Activity,
  LayoutGrid,
  Network,
  Download,
  CheckCircle2,
  AlertTriangle,
  ShieldAlert,
  FileCode2,
  ArrowLeft,
  BarChart3,
  ShieldCheck,
} from 'lucide-react';
import SimilarityHeatmap from '../../components/SimilarityHeatmap';
import GraphView from '../../components/views/GraphView';
import AnalyticsDashboard from '../../components/views/AnalyticsDashboard';

export default function ResultsPage() {
  let ctx;

  try {
    ctx = usePlagShield();
  } catch (e) {
    return (
      <div className="rounded-2xl border border-[#DCE5EF] bg-white p-12 text-center shadow-sm">
        <p className="font-bold text-[#0F172A]">Context unavailable</p>
        <p className="mt-2 text-sm text-[#64748B]">{e.message}</p>
      </div>
    );
  }

  const {
    results,
    riskThreshold = 75,
    suspiciousThreshold = 40,
    handlePairSelection,
    preferences = {},
    summaryTiles = [],
    fileStats = { total: 0, highRisk: 0, suspicious: 0, safe: 0 },
    semanticResults,
    isSemanticLoading,
    activeBatch,
  } = ctx;

  const navigate = useNavigate();

  if (!results) {
    return (
      <div className="flex min-h-[420px] flex-col items-center justify-center rounded-2xl border border-[#DCE5EF] bg-white p-12 text-center shadow-sm">
        <div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-[#EFF6FF] text-[#2563EB]">
          <Activity size={30} />
        </div>
        <h2 className="mt-5 text-xl font-bold text-[#0F172A]">
          No Analysis Results
        </h2>
        <p className="mt-2 max-w-md text-sm leading-6 text-[#64748B]">
          Open an investigation from the Analysis Library to view its results.
        </p>
        <button
          type="button"
          onClick={() => navigate('/analyses')}
          className="mt-6 inline-flex items-center gap-2 rounded-lg bg-[#2563EB] px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-[#1D4ED8]"
        >
          <ArrowLeft size={16} />
          Back to Analysis Library
        </button>
      </div>
    );
  }

  const students = results?.students || [];
  const tiles = Array.isArray(summaryTiles) ? summaryTiles : [];

  const totalPairs = Math.max(
    0,
    Number(fileStats.highRisk || 0) + Number(fileStats.suspicious || 0)
  );

  const highRiskPercent =
    totalPairs > 0
      ? Math.round((Number(fileStats.highRisk || 0) / totalPairs) * 100)
      : 0;

  const suspiciousPercent =
    totalPairs > 0
      ? Math.round((Number(fileStats.suspicious || 0) / totalPairs) * 100)
      : 0;

  return (
    <div className="space-y-6 animate-in fade-in duration-500 print:space-y-6 print:bg-white print:text-black">

      {/* ============================================================
          PRINT HEADER
      ============================================================ */}
      <div className="mb-8 hidden border-b-4 border-gray-800 pb-6 print:block">
        <div className="flex items-end justify-between">
          <div>
            <h1 className="mb-2 font-serif text-4xl font-bold text-gray-900">
              Plagiarism Analysis Report
            </h1>
            <p className="font-serif text-lg text-gray-600">
              Generated by PlagShield Engine v2.0
            </p>
          </div>

          <div className="text-right font-mono text-sm text-gray-700">
            <p className="mb-1">
              <span className="font-bold">Batch ID:</span>{' '}
              {activeBatch || 'N/A'}
            </p>
            <p className="mb-1">
              <span className="font-bold">Date:</span>{' '}
              {new Date().toLocaleDateString()}
            </p>
            <p>
              <span className="font-bold">Submissions:</span>{' '}
              {students.length}
            </p>
          </div>
        </div>
      </div>

      {/* ============================================================
          HEADER
      ============================================================ */}
      <div className="flex flex-col gap-4 rounded-2xl border border-[#DCE5EF] bg-white px-5 py-5 shadow-sm sm:flex-row sm:items-center sm:justify-between print:hidden">
        <div>
          <div className="flex items-center gap-2">
            <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-[#EFF6FF] text-[#2563EB]">
              <Network size={19} />
            </div>

            <div>
              <p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#2563EB]">
                Analysis Results
              </p>
              <h1 className="text-2xl font-bold tracking-tight text-[#0F172A]">
                Results Summary
              </h1>
            </div>
          </div>

          <p className="mt-2 text-sm text-[#64748B]">
            High-level insights, risk classification, and similarity distribution.
          </p>

          {activeBatch && (
            <div className="mt-3 inline-flex items-center gap-2 rounded-md border border-[#E2E8F0] bg-[#F8FAFC] px-2.5 py-1 text-[11px] font-medium text-[#64748B]">
              <span className="h-1.5 w-1.5 rounded-full bg-[#10B981]" />
              Batch {String(activeBatch).substring(0, 12)}
            </div>
          )}
        </div>

        <div className="flex items-center gap-2">
          <button
            type="button"
            onClick={() => navigate('/analyses')}
            className="inline-flex items-center gap-2 rounded-lg border border-[#DCE5EF] bg-white px-3.5 py-2.5 text-sm font-semibold text-[#475569] transition hover:border-[#BFDBFE] hover:bg-[#F8FAFC] hover:text-[#2563EB]"
          >
            <ArrowLeft size={16} />
            Library
          </button>

          <button
            type="button"
            onClick={() => window.print()}
            className="inline-flex items-center gap-2 rounded-lg bg-[#2563EB] px-4 py-2.5 text-sm font-semibold text-white shadow-sm transition hover:bg-[#1D4ED8]"
          >
            <Download size={16} />
            Export PDF
          </button>
        </div>
      </div>

      {/* ============================================================
          TOP SUMMARY
      ============================================================ */}
      {tiles.length > 0 && (
        <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4 print:grid-cols-4 print:gap-4 print:mb-8">
          {tiles.map((tile, idx) => (
            <div
              key={idx}
              className="group relative overflow-hidden rounded-2xl border border-[#DCE5EF] bg-white p-5 shadow-sm transition duration-200 hover:-translate-y-0.5 hover:border-[#BFDBFE] hover:shadow-md print:rounded-none print:border-gray-300 print:shadow-none"
            >
              <div className="absolute -right-5 -top-5 opacity-[0.045] transition-opacity group-hover:opacity-[0.08] print:hidden">
                <Activity size={100} />
              </div>

              <div className="relative z-10">
                <p className="mb-2 text-[10px] font-bold uppercase tracking-[0.12em] text-[#64748B]">
                  {tile.label}
                </p>

                <p className="text-3xl font-extrabold tracking-tight text-[#0F172A]">
                  {tile.value}
                </p>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* ============================================================
          ANALYSIS BREAKDOWN
      ============================================================ */}
      <section className="overflow-hidden rounded-2xl border border-[#DCE5EF] bg-white shadow-sm print:border-gray-300 print:shadow-none">
        <div className="border-b border-[#E8EEF5] bg-[#F8FAFC] px-5 py-4 sm:px-6">
          <div className="flex items-center gap-2">
            <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-[#EFF6FF] text-[#2563EB]">
              <FileCode2 size={16} />
            </div>
            <div>
              <h3 className="text-sm font-bold uppercase tracking-[0.08em] text-[#0F172A]">
                Analysis Breakdown
              </h3>
              <p className="mt-0.5 text-xs text-[#64748B]">
                Automated interpretation of the current submission batch.
              </p>
            </div>
          </div>
        </div>

        <div className="divide-y divide-[#EEF2F7] px-5 sm:px-6">
          <div className="flex items-start gap-3 py-4">
            <div className="mt-0.5 flex h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-[#F1F5F9] text-[#64748B]">
              <FileCode2 size={15} />
            </div>
            <p className="text-sm leading-6 text-[#64748B]">
              <strong className="font-semibold text-[#0F172A]">
                Batch Overview:
              </strong>{' '}
              Successfully processed and fingerprinted{' '}
              <strong className="font-semibold text-[#0F172A]">
                {fileStats.total} total files
              </strong>{' '}
              in this submission folder.
            </p>
          </div>

          {fileStats.highRisk > 0 && (
            <div className="flex items-start gap-3 py-4">
              <div className="mt-0.5 flex h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-[#FEF2F2] text-[#EF4444]">
                <ShieldAlert size={15} />
              </div>
              <p className="text-sm leading-6 text-[#64748B]">
                <strong className="font-semibold text-[#EF4444]">
                  Plagiarism Detected:
                </strong>{' '}
                <strong className="font-semibold text-[#0F172A]">
                  {fileStats.highRisk} files
                </strong>{' '}
                exhibit high-risk structural and semantic overlap exceeding the
                strict threshold ({riskThreshold}%). Immediate investigation
                recommended.
              </p>
            </div>
          )}

          {fileStats.suspicious > 0 && (
            <div className="flex items-start gap-3 py-4">
              <div className="mt-0.5 flex h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-[#FFF7ED] text-[#F59E0B]">
                <AlertTriangle size={15} />
              </div>
              <p className="text-sm leading-6 text-[#64748B]">
                <strong className="font-semibold text-[#F59E0B]">
                  Potential Overlap:
                </strong>{' '}
                <strong className="font-semibold text-[#0F172A]">
                  {fileStats.suspicious} files
                </strong>{' '}
                show suspicious similarity patterns ({suspiciousThreshold}% -
                {riskThreshold}%) that may indicate shared boilerplates or
                unauthorized collaboration.
              </p>
            </div>
          )}

          <div className="flex items-start gap-3 py-4">
            <div className="mt-0.5 flex h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-[#ECFDF5] text-[#10B981]">
              <CheckCircle2 size={15} />
            </div>
            <p className="text-sm leading-6 text-[#64748B]">
              <strong className="font-semibold text-[#10B981]">
                Safe Submissions:
              </strong>{' '}
              <strong className="font-semibold text-[#0F172A]">
                {fileStats.safe} files
              </strong>{' '}
              ({Math.round((fileStats.safe / (fileStats.total || 1)) * 100)}%)
              were found to be completely independent with no significant
              similarities to peers.
            </p>
          </div>
        </div>
      </section>

      {/* ============================================================
          FILE STATUS
      ============================================================ */}
      <div className="grid grid-cols-2 gap-4 md:grid-cols-4 print:grid-cols-4 print:gap-4">
        <StatusCard
          label="Total Files"
          value={fileStats.total}
          icon={FileCode2}
          tone="slate"
        />
        <StatusCard
          label="Safe Files"
          value={fileStats.safe}
          icon={CheckCircle2}
          tone="green"
        />
        <StatusCard
          label="Suspicious Files"
          value={fileStats.suspicious}
          icon={AlertTriangle}
          tone="amber"
        />
        <StatusCard
          label="High Risk Files"
          value={fileStats.highRisk}
          icon={ShieldAlert}
          tone="red"
        />
      </div>

      {/* ============================================================
          RISK SNAPSHOT
      ============================================================ */}
      <section className="rounded-2xl border border-[#DCE5EF] bg-white p-5 shadow-sm sm:p-6 print:hidden">
        <div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between">
          <div>
            <div className="flex items-center gap-2">
              <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-[#EFF6FF] text-[#2563EB]">
                <ShieldCheck size={16} />
              </div>
              <h3 className="text-sm font-bold uppercase tracking-[0.08em] text-[#0F172A]">
                Risk Snapshot
              </h3>
            </div>
            <p className="mt-1 text-xs text-[#64748B]">
              Distribution of flagged files requiring review.
            </p>
          </div>

          <div className="grid w-full gap-3 sm:grid-cols-2 lg:max-w-xl">
            <RiskSnapshotItem
              label="High Risk"
              value={fileStats.highRisk}
              percent={highRiskPercent}
              tone="red"
            />
            <RiskSnapshotItem
              label="Suspicious"
              value={fileStats.suspicious}
              percent={suspiciousPercent}
              tone="amber"
            />
          </div>
        </div>
      </section>

      {/* ============================================================
          ANALYTICS
      ============================================================ */}
      <section className="rounded-2xl border border-[#DCE5EF] bg-white p-4 shadow-sm sm:p-6 print:border-none print:p-0 print:shadow-none">
        <div className="mb-5 flex items-center justify-between">
          <div>
            <div className="flex items-center gap-2">
              <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-[#EFF6FF] text-[#2563EB]">
                <BarChart3 size={16} />
              </div>
              <h3 className="text-sm font-bold uppercase tracking-[0.08em] text-[#0F172A]">
                Visual Analytics
              </h3>
            </div>
            <p className="mt-1 text-xs text-[#64748B]">
              Risk, similarity, and cluster-level distribution.
            </p>
          </div>
        </div>

        <AnalyticsDashboard results={results} fileStats={fileStats} />
      </section>

      {/* ============================================================
          SIMILARITY MATRIX
      ============================================================ */}
      {students.length > 0 && (
        <section className="rounded-2xl border border-[#DCE5EF] bg-white p-4 shadow-sm sm:p-6 print:border-none print:p-0 print:shadow-none print:mb-8">
          <div className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
            <div>
              <div className="flex items-center gap-2">
                <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-[#EFF6FF] text-[#2563EB] print:hidden">
                  <LayoutGrid size={16} />
                </div>
                <h3 className="text-sm font-bold uppercase tracking-[0.08em] text-[#0F172A] print:text-lg print:normal-case print:tracking-normal">
                  Similarity Matrix
                </h3>
              </div>
              <p className="mt-1 text-xs text-[#64748B]">
                Pairwise similarity across all analyzed submissions.
              </p>
            </div>

            <span className="inline-flex w-fit items-center rounded-md border border-[#E2E8F0] bg-[#F8FAFC] px-2.5 py-1 text-[11px] font-semibold text-[#64748B]">
              {students.length} submissions
            </span>
          </div>

          <div className="overflow-hidden rounded-xl border border-[#DCE5EF] bg-[#F8FAFC] p-3 sm:p-4 print:rounded-none print:border-gray-300 print:bg-white">
            <SimilarityHeatmap
              data={results}
              thresholds={{
                highRisk: riskThreshold,
                suspicious: suspiciousThreshold,
              }}
              animateCells={preferences?.animateHeatmap ?? true}
              onPairSelect={(pair) => {
                if (handlePairSelection) handlePairSelection(pair);
                navigate('/analyses/latest/compare');
              }}
            />
          </div>
        </section>
      )}

      {/* ============================================================
          SEMANTIC GRAPH
      ============================================================ */}
      <section className="rounded-2xl border border-[#DCE5EF] bg-white p-4 shadow-sm sm:p-6 print:border-none print:p-0 print:shadow-none">
        <div className="mb-5">
          <div className="flex items-center gap-2">
            <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-[#EFF6FF] text-[#2563EB] print:hidden">
              <Network size={16} />
            </div>
            <h3 className="text-sm font-bold uppercase tracking-[0.08em] text-[#0F172A] print:text-lg print:normal-case print:tracking-normal">
              Semantic Graph
            </h3>
          </div>
          <p className="mt-1 text-xs text-[#64748B]">
            Visual relationship map of semantically similar submissions.
          </p>
        </div>

        <div className="overflow-hidden rounded-xl border border-[#DCE5EF] bg-[#F8FAFC] print:border-none print:bg-white">
          <GraphView
            semanticResults={semanticResults}
            isSemanticLoading={isSemanticLoading}
          />
        </div>
      </section>
    </div>
  );
}

/* ================================================================
   STATUS CARD
================================================================ */

function StatusCard({ label, value, icon: Icon, tone }) {
  const tones = {
    slate: {
      box: 'bg-[#F8FAFC] border-[#E2E8F0]',
      icon: 'bg-[#F1F5F9] text-[#64748B]',
      label: 'text-[#64748B]',
      value: 'text-[#0F172A]',
    },
    green: {
      box: 'bg-[#F0FDF9] border-[#D1FAE5]',
      icon: 'bg-[#ECFDF5] text-[#10B981]',
      label: 'text-[#059669]',
      value: 'text-[#059669]',
    },
    amber: {
      box: 'bg-[#FFFBEB] border-[#FDE68A]',
      icon: 'bg-[#FFF7ED] text-[#F59E0B]',
      label: 'text-[#D97706]',
      value: 'text-[#D97706]',
    },
    red: {
      box: 'bg-[#FFF7F7] border-[#FECACA]',
      icon: 'bg-[#FEF2F2] text-[#EF4444]',
      label: 'text-[#DC2626]',
      value: 'text-[#DC2626]',
    },
  };

  const t = tones[tone] || tones.slate;

  return (
    <div className={`rounded-2xl border p-5 shadow-sm ${t.box}`}>
      <div className="flex items-start justify-between gap-3">
        <div>
          <p className={`text-[10px] font-bold uppercase tracking-[0.12em] ${t.label}`}>
            {label}
          </p>
          <p className={`mt-2 text-3xl font-extrabold tracking-tight ${t.value}`}>
            {value}
          </p>
        </div>

        <div className={`flex h-9 w-9 items-center justify-center rounded-lg ${t.icon}`}>
          <Icon size={17} />
        </div>
      </div>
    </div>
  );
}

/* ================================================================
   RISK SNAPSHOT ITEM
================================================================ */

function RiskSnapshotItem({ label, value, percent, tone }) {
  const isRed = tone === 'red';

  return (
    <div className="rounded-xl border border-[#E2E8F0] bg-[#F8FAFC] p-3.5">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <span
            className={`h-2.5 w-2.5 rounded-full ${
              isRed ? 'bg-[#EF4444]' : 'bg-[#F59E0B]'
            }`}
          />
          <span className="text-xs font-semibold text-[#334155]">{label}</span>
        </div>

        <span className="text-xs font-bold text-[#0F172A]">
          {value}
        </span>
      </div>

      <div className="mt-2 h-1.5 overflow-hidden rounded-full bg-[#E8EEF5]">
        <div
          className={`h-full rounded-full transition-all ${
            isRed ? 'bg-[#EF4444]' : 'bg-[#F59E0B]'
          }`}
          style={{ width: `${Math.min(100, Math.max(0, percent))}%` }}
        />
      </div>

      <p className="mt-1.5 text-[10px] text-[#64748B]">
        {percent}% of flagged files
      </p>
    </div>
  );
}
