spring.application.name=plagshield-backend
server.port=8082

# Database Configuration (MongoDB)
spring.data.mongodb.uri=mongodb://localhost:27017/plagshield

# File Storage
file.upload-dir=storage/uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
